### PR TITLE
added: Pre-fill "Start from Scratch" for new bounties with the following headers

### PR DESCRIPTION
**Pull request by suhasasumukh**
## What does this PR do?
The bounty description dialog box has been pre-filled with the given headings,

• About the Bounty & Scope
• Rewards
• Judging Criteria
• Submission Requirements
• Resources

## What are the relevant issues?
fixes https://github.com/SuperteamDAO/earn/issues/274

### CODE REVIEW

**Review by a20hek — CHANGES_REQUESTED** [review]
image

**Comment by suhasasumukh** [comment]
> image

@a20hek I have updated it now it should start from a newline

**Comment by a20hek** [comment]
> > image
> 
> @a20hek I have updated it now it should start from a newline

it is not just about the new line
it is also about them not being H1

**Comment by suhasasumukh** [comment]
> > > image
> > 
> > 
> > @a20hek I have updated it now it should start from a newline
> 
> it is not just about the new line it is also about them not being H1

fixed it

**Review by a20hek — CHANGES_REQUESTED** [review]
has prettier errors

**Comment by a20hek** [comment]
also, this isn't markdown
this has to be `<h2>`

**Comment by suhasasumukh** [comment]
> also, this isn't markdown this has to be `<h2>`

hence updated with .map((heading)

**Comment by suhasasumukh** [comment]
image
ran npx prettier

**Comment by jaybuurdd** [comment]
> > also, this isn't markdown this has to be `<h2>`
> 
> hence updated with .map((heading)

?

```
.map((heading) => `<h2>${heading}</h2>`)
````

**Pull request closed without merging**
