### PR TITLE
FEAT: "Allow sponsors to edit there profile"

### PR DESCRIPTION
**Pull request by KshitijBhardwaj18**
## What does this PR do?'
Sponsors would be able to edit their profile details from the sponsor dashboard. 

## Where should the reviewer start?
Reviewer should look for the edit/sponsor route to evaluate the functionality.

## How should this be manually tested?
Get your self logged in with a sponsor profile. Navigate to dashboard and click on the edit icon just adjcen to the name of sponsor

## Screenshots (if appropriate)
sponsoredit

refs: #477

### CODE REVIEW

**Comment by a20hek** [comment]
buddy @KshitijBhardwaj18 your PR looks eerily similar to https://github.com/SuperteamDAO/earn/pull/487
can you explain what's up?

**Comment by a20hek** [comment]
down to the diff and number of lines changed

**Comment by KshitijBhardwaj18** [comment]
Yes, picked up the code from that pr. Seemed mostly correct  working on the background of inputs that are prefilled further @a20hek

**Comment by a20hek** [comment]
> Yes, picked up the code from that pr. Seemed mostly correct working on the background of inputs that are prefilled further @a20hek

but why would you copy the code?

**Comment by a20hek** [comment]
@KshitijBhardwaj18 ?

**Review by a20hek — COMMENTED** [review]
reason for closing PR: is a duplicate

**Pull request closed without merging**
