### PR TITLE
Added a Link to the Earn logo in the Footer

### PR DESCRIPTION
**Pull request by suhasasumukh**
## What does this PR do?

You can now "right click + open link in new tab" by clicking on the Earn logo in the footer.

### CODE REVIEW

**Comment by a20hek** [comment]
@suhasasumukh you have to fix your eslint issues buddy. lmk if you need my help with that

**Review by a20hek — CHANGES_REQUESTED** [review]
@suhasasumukh you have to fix your eslint issues buddy. lmk if you need my help with that

**Comment by suhasasumukh** [comment]
> @suhasasumukh you have to fix your eslint issues buddy. lmk if you need my help with that

sure i'll try and fix the lint errors

**Review by a20hek — CHANGES_REQUESTED** [review]
same thing over again; it's an issue with your ide. i might know what it might be. lmk if you wanna get on a call regarding this

**Comment by suhasasumukh** [comment]
> same thing over again; it's an issue with your ide. i might know what it might be. lmk if you wanna get on a call regarding this

I haven't pushed the commits yet, I just updated the branch

**Comment by a20hek** [comment]
closing this due to inactivity, has been implemented in one of the feature branches where we added link prefetching to all link across the site to prevent re-renders.

**Pull request closed without merging**
