### PR TITLE
[TalentProfile][Fix] After uploading PoW, now we update the talentFeed

### PR DESCRIPTION
**Pull request by lucasdemoreno**
## What does this PR do?

Before, when user uploaded a new PoW through the Add Project in their profile page, we didn't show the newly created PoW.
After, now we do. There was a bug on how we updated the talent variable in that React component and also the shape of the object created is not the same one as the one we get from the backend. Missing lots of fields.

#### Solution:
- Completely refresh the page to avoid managing unnecessary partial states.

## Where should the reviewer start?

The flow starts like this:
```
AddProject.tsx -> onSubmit() -> t/[slug]/index.tsx addNewPow()
```

## How should this be manually tested?
Go to your profile, click on +ADD (next to Proof of Work), complete the form, click on AddProject.
Expected result: no reload should be needed. The PoW should be added to the profile automatically.

image
image

## Any background context you want to provide?

No. First contribution to this repo and to Superteam

## What are the relevant issues?

No issue submitted for this so far.

## Screenshots (if appropriate)

Uploaded above

### CODE REVIEW

**Review by a20hek — COMMENTED** [review]
is it necessary to add a state to make this work?

**Comment by lucasdemoreno** [comment]
> is it necessary to add a state to make this work?

@a20hek now that I have tested it, it works. 
The only way for react to trigger a rerender in this case is to update a variable created with `setState`.
```typescript
// This is executed outside of the react lifecycle. 
// The react component doesn't keep track of those changes.
talent.feed = [newPow, ...talent.feed]
```
I updated the description of the ticket and there are 2 solutions:
- Refresh the page entirely.
- Trigger a get of all the talent again inside the `AddProject` modal or inside the `addNewPow()` with another `useState()`

**Comment by lucasdemoreno** [comment]
Also, somebody wrote a post about something similar here:
https://www.joshwcomeau.com/nextjs/refreshing-server-side-props/

**Review by a20hek — APPROVED** [review]
LGTM!

**Pull request merged**
