### PR TITLE
FEAT: Updated bounties page to only consist of bounties that belongs to user's location and global

### PR DESCRIPTION
**Pull request by Mihir867**
## What does this PR do?
This PR updates the code to filter bounties so that only those which belong to the user's location or are marked as global are shown to the user. This ensures that users see relevant bounties based on their location.

## Where should the reviewer start?
The reviewer should start by looking at the changes made in the /api/listings/index.tsx, particularly the OR clause is used. Ensure that the filtering logic using OR with region: 'GLOBAL' and region: location is correctly implemented.

## How should this be manually tested?

1. Set up your local environment to run the Next.js application.
2. Ensure you have the Prisma client configured and connected to the database.
3. Run the application and navigate to the page where bounties are listed.
4. Test the filtering by checking if bounties shown belong to either 'GLOBAL' or the specific user location.
5. You can change the user location to different values and verify if the filtering works as expected.

## Any background context you want to provide?
The goal of this update is to enhance the user experience by ensuring that users only see bounties that are relevant to them based on their location. Previously, users might have seen bounties from regions that were not applicable to them. This change makes the application more user-centric and improves engagement.

## What are the relevant issues?
There may have been previous issues or feature requests related to filtering bounties based on user location. If any specific issue numbers or tickets are related to this change, they should be referenced here (e.g., Issue #630 ).

## Screenshots (if appropriate)
image
As illustrated in the screenshot below, there are three bounties listed: one global, one from India, and one from the UK. With the new filtering logic applied, the bounties page will display only the global and India bounties, excluding the UK bounty: - 

image

### CODE REVIEW

**Review by a20hek — COMMENTED** [review]
can do this for homepage as well?

pull the latest changes, and you can find the file at `/pages/api/listings/homepage`

**Comment by Mihir867** [comment]
> can do this for homepage as well?
> 
> pull the latest changes, and you can find the file at `/pages/api/listings/homepage`

 Sure, I will do it :)

**Comment by Mihir867** [comment]
Hi, I have committed the changes related to home page, Let me know if anything, Appreciate the feedback !!

**Comment by Mihir867** [comment]
Hey, Please ignore the above changes and see this final commit, Thanks :)

**Review by a20hek — CHANGES_REQUESTED** [review]
why package-lock?
we use pnpm 

please remove this file

**Comment by Mihir867** [comment]
Yes done

**Review by a20hek — CHANGES_REQUESTED** [review]
i think you added this feature for the bounties page but missed the projects page

**Comment by Mihir867** [comment]
> i think you added this feature for the bounties page but missed the projects page

I added it for the bounties page and homepage, and will add it for projects too

**Comment by Mihir867** [comment]
Hi, I have updated the same, Can you check ?

**Comment by a20hek** [comment]
there seems to be some bugs with this implementation:

Pasted Graphic

**Comment by Mihir867** [comment]
I will check this

**Pull request closed without merging**
