### PR TITLE
Twitter logo updated in the footer

### PR DESCRIPTION
**Pull request by suhasasumukh**
Added the new updated logo of the Twitter, the X SVG icon

## What does this PR do?
Updated icon of twitter on the footer

### CODE REVIEW

**Comment by a20hek** [comment]
please fix the lint errors

**Review by a20hek — CHANGES_REQUESTED** [review]
please fix the lint errors

**Comment by suhasasumukh** [comment]
hey @a20hek could you review it now?

**Comment by suhasasumukh** [comment]
hey @a20hek the lint error doesn't originate from my code

**Comment by a20hek** [comment]
> hey @a20hek the lint error doesn't originate from my code

it did. i think @DitherWither fixed it. 
please change twitter logo in all places like mentioned in the issue

**Comment by suhasasumukh** [comment]
hey @a20hek please check this https://github.com/SuperteamDAO/earn/pull/282/commits/a78559c2f9bc41f63e5e2792b253c0da3218eb63

I have updated the svg file of twitter

**Comment by a20hek** [comment]
> hey @a20hek please check this [a78559c](https://github.com/SuperteamDAO/earn/commit/a78559c2f9bc41f63e5e2792b253c0da3218eb63)
> 
> I have updated the svg file of twitter

that lgtm. to maintain brand consistency across the web app, please also update the Twitter logo wherever else it might be appearing. thanks!

**Comment by suhasasumukh** [comment]
> > hey @a20hek please check this [a78559c](https://github.com/SuperteamDAO/earn/commit/a78559c2f9bc41f63e5e2792b253c0da3218eb63)
> > I have updated the svg file of twitter
> 
> that lgtm. to maintain brand consistency across the web app, please also update the Twitter logo wherever else it might be appearing. thanks!

@a20hek sure will do it,
Thank you for the opprtunity

**Comment by suhasasumukh** [comment]
> > hey @a20hek please check this [a78559c](https://github.com/SuperteamDAO/earn/commit/a78559c2f9bc41f63e5e2792b253c0da3218eb63)
> > I have updated the svg file of twitter
> 
> that lgtm. to maintain brand consistency across the web app, please also update the Twitter logo wherever else it might be appearing. thanks!

hey @a20hek I found a new file of the twitter svg under the assets folder and i have updates it,
Please take a look at this https://github.com/SuperteamDAO/earn/commit/a3eeb1d131af9d5dd8067b10660a10cbda3cebd6

**Comment by a20hek** [comment]
> Author

will review after you clarify some of my doubts:
- do the aseets adhere to our theme?
- considering you've replaced the image, have you checked if the replaced image is breaking the layout in any part of the website that they've been used
- are you sure that there are no occurrences remaining of the old Twitter logo?

**Comment by suhasasumukh** [comment]
> > Author
> 
> will review after you clarify some of my doubts:
> 
> * do the aseets adhere to our theme?
> * considering you've replaced the image, have you checked if the replaced image is breaking the layout in any part of the website that they've been used
> * are you sure that there are no occurrences remaining of the old Twitter logo?

@a20hek I have updated the .png files and .svg image where ever I found the file

**Review by a20hek — CHANGES_REQUESTED** [review]
edit profile page, and profile page still has the old twitter logo

**Comment by suhasasumukh** [comment]
sure @a20hek i will fix these

**Comment by a20hek** [comment]
> > LGTM, please squash the commits
> 
> I don't have merge access

you can squash commits without merge access iirc

**Comment by suhasasumukh** [comment]
> > > LGTM, please squash the commits
> > 
> > 
> > I don't have merge access
> 
> you can squash commits without merge access iirc

not available to squash the commit :(
image

**Comment by a20hek** [comment]
you have to do it via your fork @suhasasumukh

**Comment by suhasasumukh** [comment]
> you have to do it via your fork @suhasasumukh

i'm not sure on how to squash merge via my fork

**Comment by suhasasumukh** [comment]
@a20hek squash and merge from your side

**Pull request merged**
