### PR TITLE
added global option with icon

### LINKED ISSUE #682: Regions Feature missing "global" as an option
## Expected Behavior
The recent `regions` feature should show the "global" option among the selectable regions.

Screenshot_20240810_015234

## Actual Behavior
However once user selects a region, the global option dissapears. this means user has to either remove the extra path on the address bar or reload the bounties/projects page to see the globally available bounties/projects again.

Screenshot_20240810_015150

@a20hek

### PR DESCRIPTION
**Pull request by OmChillure**
## What does this PR do?
fixes #682 

## Where should the reviewer start?
Can start from constants/Superteam.ts.

## How should this be manually tested?
By going to contstans/Superteam.ts.

## Any background context you want to provide?
I added an object inside  the array to render a option of Global, to navigate to home page with ease. I also added the icon.

## What are the relevant issues?
Once user selects a region, the global option dissapears. this means user has to either remove the extra path on the address bar or reload the bounties/projects page to see the globally available bounties/projects again.

## Screenshots (if appropriate)
Before 
test

After
Screenshot 2024-09-15 122117

### CODE REVIEW

**Review by a20hek — COMMENTED** [review]
why are we closing and opening prs over and over again for changes?
do them in the same PR unless absolutely necessary please
i want the stream of conversation and changes to be there

**Comment by OmChillure** [comment]
ohh sorry , I will keep this in mind! I will do them in the same from next.

**Review by a20hek — CHANGES_REQUESTED** [review]
was away for a few weeks; 
adding global as a superteam does this:
image

also, the global icon isn't an ios icon

**Comment by a20hek** [comment]
closing due to inactivity

**Pull request closed without merging**
