### PR TITLE
feat: new sponsor landing page

### PR DESCRIPTION
**Pull request by JayeshVP24**
## Screenshots (if appropriate)

### CODE REVIEW

**Comment by JayeshVP24** [comment]
@a20hek this is ready to be merged

**Review by a20hek — COMMENTED** [review]
did you minify all images @JayeshVP24 ?

**Comment by JayeshVP24** [comment]
> did you minify all images @JayeshVP24 ?

nope, what tool do u use to this without quality loss?

**Comment by JayeshVP24** [comment]
@a20hek done!

**Pull request merged**
