### PR TITLE
added global as a option

### LINKED ISSUE #682: Regions Feature missing "global" as an option
## Expected Behavior
The recent `regions` feature should show the "global" option among the selectable regions.

Screenshot_20240810_015234

## Actual Behavior
However once user selects a region, the global option dissapears. this means user has to either remove the extra path on the address bar or reload the bounties/projects page to see the globally available bounties/projects again.

Screenshot_20240810_015150

@a20hek

### PR DESCRIPTION
**Pull request by Mihir867**
## What does this PR do?

This fixes #682 

## Where should the reviewer start?
You can start by checking footer section changes

## How should this be manually tested?

1. Navigate to the country selector and verify that "Global" is the default option.
2. Select any country from the dropdown.
3. Re-open the dropdown and confirm that "Global" appears as an option, allowing you to switch back to it.

## Any background context you want to provide?
Nope

## What are the relevant issues?
Fixes #682

## Screenshots (if appropriate)

before -
global was not a option once a country is selected

after-

Screenshot 2024-11-09 at 12 54 01 PM

### CODE REVIEW

**Comment by a20hek** [comment]
lgtm, except, use this icon instead:
https://emojipedia.org/globe-showing-asia-australia

**Comment by Mihir867** [comment]
> lgtm, except, use this icon instead: https://emojipedia.org/globe-showing-asia-australia

yes done

**Review by a20hek — CHANGES_REQUESTED** [review]
i meant using the asset (png) 
you can find the asset I am looking for on this link. download a 256x256 png and use that instead

https://www.svgrepo.com/svg/396564/globe-showing-europe-africa

**Comment by Mihir867** [comment]
> i meant using the asset (png) you can find the asset I am looking for on this link. download a 256x256 png and use that instead
> 
> https://www.svgrepo.com/svg/396564/globe-showing-europe-africa

ooh, okay done

**Review by a20hek — CHANGES_REQUESTED** [review]
can you close this start a new PR? the base branch from where you checked out had to be the `staging` branch

also, the globe image needs to be compressed and resized to 256x256

**Pull request closed without merging**
