### PR TITLE
Sorted Comments in Reverse Chronological order

### PR DESCRIPTION
**Pull request by ATREAY**
## What does this PR do?
Sorted Comments under each bounty in Reverse Chronological order

## What are the relevant issues?
closes: #271

## Screenshots (if appropriate)
reversed comments

### CODE REVIEW

**Review by a20hek — CHANGES_REQUESTED** [review]
please fix the lint errors

**Comment by ATREAY** [comment]
Hey @a20hek, I've sorted out the lint error. Could you give it a look and tell me if there's anything else left to do?

**Comment by a20hek** [comment]
@ATREAY the comments are still in displayed in the chronological order.

**Comment by ATREAY** [comment]
Hey @a20hek, as per the issue "newest comments should show up at the bottom," I left a comment right under yours, and it ended up at the very bottom of all the comments. I believe this is the right behavior, but if I'm mistaken, please let me know.

Here is the screenshot:
comments

**Comment by a20hek** [comment]
> Hey @a20hek, as per the issue "newest comments should show up at the bottom," I left a comment right under yours, and it ended up at the very bottom of all the comments. I believe this is the right behavior, but if I'm mistaken, please let me know.
> 
> Here is the screenshot: comments

oh, i think there might have been some confusion. lemme check with the team and get back to you. sorry for the inconvenience @ATREAY

**Comment by ATREAY** [comment]
Hello @a20hek, do you have any updates?

**Pull request closed without merging**
