### PR TITLE
fix: use next link with chakra link

### LINKED ISSUE #249: App reloads on route change
https://www.loom.com/share/509324ec5bc944809e4223f0995450b4?sid=07bdb726-6700-4536-801b-8b624eb5a42f

### PR DESCRIPTION
**Pull request by bhagyamudgal**
- We were using chakra ui link component and whenever we go to another page app was reloading which should not happen with SPA
- So I used NextLink with chakra ui link component using as property

fixes #249 

Issue Video
https://www.loom.com/share/509324ec5bc944809e4223f0995450b4?sid=07bdb726-6700-4536-801b-8b624eb5a42f

### CODE REVIEW

**Comment by bhagyamudgal** [comment]
@a20hek Please review this when you get time. Thanks!

**Comment by bhagyamudgal** [comment]
We were using `Link` with Flex earlier, so what's the problem with using `NextLink`?

**Comment by bhagyamudgal** [comment]
Also I was not able to test these changes locally because of lack of `env`, so will check once you will provide the `env`. Let me know if there are any issues using `NextLink` with `Flex`. Then we can use `NextLink` as Wrapper for `Flex`

**Comment by dhruvsol** [comment]
@bhagyamudgal  @a20hek Something I learned when I was fixing cubik stuff 

`as={NextLink}` This will not import the special property like prefetch and other things by nextjs. when you do `as={NextLink}` this will just pass down the props nothing else. If you just wrap it in `<NextLink></NextLink> this will give you better results.

**Comment by bhagyamudgal** [comment]
Thanks for this insight @dhruvsol bro. Will get this fixed

**Comment by bhagyamudgal** [comment]
@a20hek made the change, please check when you are available, thanks!

**Comment by a20hek** [comment]
> @a20hek made the change, please check when you are available, thanks!

have some issues:
1. layout needs to be fixed
image
2. Pages not getting re-rendered on navigation to skill-specific bounty pages.

**Comment by bhagyamudgal** [comment]
will fix in the morning

**Comment by bhagyamudgal** [comment]
@a20hek fixed the issues, please check. Thanks!

**Review by a20hek — APPROVED** [review]

**Comment by a20hek** [comment]
@bhagyamudgal the pages are still not getting rerendered.

**Comment by bhagyamudgal** [comment]
https://github.com/SuperteamDAO/earn-frontend-v2/pull/248#issuecomment-1709645193

I don't get this. Can you please elaborate or share a loom?

**Pull request closed without merging**
