### PR TITLE
Blink integration for sponsors

### PR DESCRIPTION
**Pull request by Praharx**
## What does this PR do?
Facilitates the user with blink creation without any extra effort. The blink url is available when they publish the bounty listing.
## Where should the reviewer start?
CreateListing.tsx & ListingSuccessModal.tsx  have the major implementation for the PR.
## How should this be manually tested?
Locally setting up the project and then creating a new bounty as a sponsor.
## Any background context you want to provide?
We previously talked with pratik and aditya about the integration. Just a working implementation for the same.
## Screenshots (if appropriate)
A demo video on how things are working actually.

https://github.com/user-attachments/assets/185db3fe-3066-4910-b8bc-84fee9849245

### CODE REVIEW

**Review by a20hek — CHANGES_REQUESTED** [review]
Remove `package-lock.json` please.
We use pnpm.

**Comment by Praharx** [comment]
> Remove `package-lock.json` please. We use pnpm.

done.

**Comment by Praharx** [comment]
hey just wanted to know do you want any changes or anywhere I should iterate to make the PR acceptable?

**Comment by a20hek** [comment]
thank you for your contribution

after reviewing the PR, we’ve decided to close it for the following reasons:
- we dont see a clear use case for adding the blink feature at this time
- there’s significant validation and other complex logic involved in form submission, which I dont think can be properly integrated with this approach
- we currently dont recognize sites like bountyspread
- additionally, there have been changes made to files such as tsconfig and package.json, which should not be modified in this context


we appreciate your efforts and encourage you to explore other areas for contribution. Please feel free to reach out if you have any questions or need further clarification!

**Pull request closed without merging**
