### PR TITLE
fix emailModelPreferences   

### PR DESCRIPTION
**Pull request by Code-Parth**
## Issue in Website

[YouTube Explanation](https://www.youtube.com/watch?v=Ec4Ef6tMlGw)

## Issue Cause

after closing the modal it will change the url to undefined path

### Issue at [`UserMenu.tsx`](https://github.com/SuperteamDAO/earn/blob/7f3be20362fbf42655ba2776be08b2fd1bfc9c77/src/components/shared/UserMenu.tsx#L55)

```tsx
const handleClose = () => {
    onClose();
    router.push(router.pathname, undefined, { shallow: true });
};
```

### Solution

```tsx
const handleClose = () => {
    onClose();
};
```

### CODE REVIEW

**Review by a20hek — CHANGES_REQUESTED** [review]
shallow routing is important to us; perhaps an `if` condition to trigger it would be better

**Comment by Code-Parth** [comment]
I updated to shallow routing

**Review by a20hek — CHANGES_REQUESTED** [review]
we are using the pages router (usePathname is native to app router, so is "use client")

**Comment by Code-Parth** [comment]
I checked in my localhost working properly but anyway I will figure it out.

Basically, the problem is from the router.pathname

**Review by a20hek — CHANGES_REQUESTED** [review]
you are trying to push a lot more changes than required.

**Comment by Code-Parth** [comment]
Ser, I'm facing an issue when I change that and check for the build command then show a prettier error after this, I run `pnpm run format` and then build completely without any error so I commit it. 

Any suggestion for what can I do in this?

We need to change only one word
Here is the [Line](https://github.com/Code-Parth/earn/blob/48dea9c389c154281860562c0c78dfc1257aa843/src/components/shared/UserMenu.tsx#L57)

**Comment by a20hek** [comment]
> Ser, I'm facing an issue when I change that and check for the build command then show a prettier error after this, I run `pnpm run format` and then build completely without any error so I commit it.
> 
> Any suggestion for what can I do in this?
> 
> We need to change only one word Here is the [Line](https://github.com/Code-Parth/earn/blob/48dea9c389c154281860562c0c78dfc1257aa843/src/components/shared/UserMenu.tsx#L57)

close this PR and start a new one if you are finding this too difficult

**Pull request closed without merging**
